title: Alua Kinzhebayeva
description: Software development blog

url: http://alua-kinzhebayeva.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: Alua-Kinzhebayeva
   email: Alua.Kinzhebayeva@gmail.com

google_analytics: "UA-66923596-1"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
